export const patientTemplate = [
  {
    _id: "1",
    disease: "хвороба",
    reviewDate: `1.1.2021`,
    cardNumber: `1`,
    name: `Тестовий Пацієнт Батькович`,
    doctor: "Особистий лікар",
    toothCasual: "55",
    start1: "",
    start2: "день",
    pregnancy: 1,
    childbirth: 1,
    birthWeight: "3600",
    condition: "задовільний",
    weight: "55",
    age: 17,
    crownDestruction: "частково зруйнована",
    inflammationArea: "54,55",
    planned: false,
    drugs: [
      "ібупрофен, по 200 мг, двічі на добу",
      "Лоратадин, сироп, по 5 мл, 1 р/д"
    ],
    protocolNumber: "1",
    operationDate: "1.1.2025",
    operationTime: "12.00",
    pliers: "",
    elevator: "",
    duration: "15",
    surgeon: "Хірург",
    assistant: "Асистент",
    anesthetist: "Анестезіолог",
    woundArea: "",
    woundSide: "",
    injuryDate: "",
    injuryTime: "",
    injuryReason: "",
    woundType: "",
    woundLength: "",
    woundWidth: "",
    woundDepth: "",
    woundForm: "",
    woundLedges: "",
    woundBleeding: "",
    woundAliens: "",
    sutureType: "",
    sutureMaterial: "",
    sutureSize: "",
    startDay: "",
    startMonth: "",
    startYear: "",
    operationDataSend: true,
    complaintsContent: "на біль.",
    anamnesisMorbiContent: "хворіє 1 день.",
    anamnesisVitaeContent: "пацієнт...",
    statusPraesensContent: "соматично здоровий",
    shortStatusContent: "обличчя симетричне",
    statusLocalisContent: "обличчя симетричне",
    diagnosis: "періодонтит",
    diagnosisCap: "Періодонтит",
    operationName: "НАЗВА ОПЕРАЦІЇ",
    operationNameCap: "НАЗВА ОПЕРАЦІЇ",
    operationContent: "Місцеве знеболення...",
    perioTeeth: "",
    heartRate: 70,
    respiratoryRate: 20,
    lastTime: "15.00",
    someDayContent: "Обличчя симетричне...",
    lastDayContent: "Обличчя симетричне...",
    diaryList: [
      {
        date: `1.1.2021`,
        workDay: true
      },
      {
        date: `1.1.2021`,
        workDay: true
      },
      {
        date: `1.1.2021`,
        workDay: true
      }
    ],
    changedList: [1, 2, 3],
    epicrisisDataSend: false,
    extractDataSend: false,
    anestesiaType: `Загальне знеболення`,
    abscessType: "",
    abscessArea: "",
    abscessSide: "",
    abscessReason: "",
    abscessTooth: "",
    cystTooth: "",
    rootSealed: ""
  }
];
